### PR TITLE
Updated Layer ID range guess

### PR DESCRIPTION
**Pull request by Montspy**
Fixes LayerHopper on Faerlina after 7/14 maintenance

### CODE REVIEW

**Comment by Montspy** [comment]
Confirmed to fix layer detection on dozens of guildies, please merge

**Comment by psynct** [comment]
fixed in v1.5.7

**Comment by psynct** [comment]
Sorry didn't see the PR until I had already made the same exact fix from a comment on curseforge

**Comment by Montspy** [comment]
No problem, thanks for releasing a new version for everyone!
I'm glad we came up to the same fix :)

**Pull request closed without merging**
